version: '3.7'
services:
  aws:
    image: localstack/localstack:0.12.10
    container_name: aws
    environment:
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - HOSTNAME_EXTERNAL=aws
      - DEBUG=1
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8055:8080"
  integration-tests:
    build:
      context: .
      target: deps
    volumes:
      - .:/build
    depends_on:
      - aws
    environment:
      - URL=http://aws:4566
    command: ./scripts/integration-tests.sh
